<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> cb293e9 (Hello)
=======
>>>>>>> cb293e9 (Hello)
// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Header from "./components/Header";
<<<<<<< HEAD
<<<<<<< HEAD
=======
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
>>>>>>> bb0efd9 (Initial commit from Create Next App)
=======
>>>>>>> cb293e9 (Hello)
=======
>>>>>>> cb293e9 (Hello)
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
  title: "Progforum",
  description: "Forum for programming discussions and resources",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> bb0efd9 (Initial commit from Create Next App)
=======
  title: "Progforum",
  description: "Forum for programming discussions and resources",
>>>>>>> cb293e9 (Hello)
=======
  title: "Progforum",
  description: "Forum for programming discussions and resources",
>>>>>>> cb293e9 (Hello)
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
        <Header />
=======
>>>>>>> bb0efd9 (Initial commit from Create Next App)
=======
        <Header />
>>>>>>> cb293e9 (Hello)
=======
        <Header />
>>>>>>> cb293e9 (Hello)
        {children}
      </body>
    </html>
  );
}
